/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemarestaurantepresentacion.ModuloProductos;

import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemarestaurantedominio.Ingrediente;
import sistemarestaurantedominio.Producto;
import sistemarestaurantedominio.UnidadMedidaIngrediente;
import sistemarestaurantedominio.dtos.NuevoIngredienteProductoDTO;
import sistemarestaurantedominio.dtos.NuevoProductoDTO;
import sistemarestaurantenegocio.IIngredientesProductosBO;
import sistemarestaurantenegocio.excepciones.NegocioException;
import sistemarestaurantepersistencia.DAOS_implementaciones.IngredientesDAO;
import sistemarestaurantepersistencia.DAOS_implementaciones.ProductosDAO;
import sistemarestaurantepresentacion.frmMenuPrincipal;

/**
 *
 * @author gael_
 */
public class frmAnadirIngredienteProducto extends javax.swing.JFrame {

    private IIngredientesProductosBO ingredientesProductosBO;
     private static final Logger LOG = Logger.getLogger(frmAnadirIngredienteProducto.class.getName());
    
    /**
     * Creates new form frmAnadirIngredienteProducto
     */
    public frmAnadirIngredienteProducto() {
        initComponents();
        LlenarComboBoxProductos();
        LlenarComboBoxIngrediente();
    }
    


    private void LlenarComboBoxProductos(){
        ProductosDAO productosDAO = new ProductosDAO();
        List<Producto> productos = productosDAO.obtenerProductos();
        
        jComboBoxProducto.removeAllItems();
        
        if (productos.isEmpty()) {
            jComboBoxProducto.addItem("No hay productos disponibles");
        return;
        }

        for (Producto producto : productos) {
            jComboBoxProducto.addItem(producto.getNombre()); 
        }
    }
   
    private void LlenarComboBoxIngrediente(){
        IngredientesDAO ingredienteDAO = new IngredientesDAO();
        List<Ingrediente> ingredientes = ingredienteDAO.obtenerIngredientes();
        
        jComboBoxIngrediente.removeAllItems();
        
        
        for(Ingrediente ingrediente : ingredientes){
        String nombreCompleto = ingrediente.getNombre() + " - " + ingrediente.getUnidadMedida();
        jComboBoxIngrediente.addItem(nombreCompleto);
    }
    }
    
    public Ingrediente enviarIngredienteSeleccionado(){
        String seleccionado = (String) jComboBoxIngrediente.getSelectedItem();
        
        if (seleccionado != null) {
            IngredientesDAO ingredienteDAO = new IngredientesDAO();
            List<Ingrediente> ingredientes = ingredienteDAO.obtenerIngredientes();

            for (Ingrediente ingrediente : ingredientes) {
                String nombreCompleto = ingrediente.getNombre() + " - " + ingrediente.getUnidadMedida();
                if (nombreCompleto.equals(seleccionado)) {
                    return ingrediente;
                }
            }
        }
        return null;
    }
    
    private void anadirIngredienteProducto(){
        
        Producto productoSeleccionado = (Producto) this.jComboBoxProducto.getSelectedItem();
        Ingrediente ingredienteSeleccionado = enviarIngredienteSeleccionado();
        Float cantidad = Float.parseFloat(this.jTextFieldCantidad.getText());
        NuevoIngredienteProductoDTO nuevoIP = new NuevoIngredienteProductoDTO(productoSeleccionado,  ingredienteSeleccionado,  cantidad);

        try{
            this.ingredientesProductosBO.registrarIngredienteProductoBO(nuevoIP);
            JOptionPane.showMessageDialog(this, "Exito al regisrar el ingrediente-producto ", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
                        
        } catch(NegocioException e){
            LOG.severe("No fue posible registrar el ingrediente-producto " + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }
    
    private void limpiarFormulario(){
        this.jTextFieldCantidad.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelANADIRINGREDIENTES = new javax.swing.JLabel();
        jLabelIngrediente = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jComboBoxIngrediente = new javax.swing.JComboBox<>();
        jTextFieldCantidad = new javax.swing.JTextField();
        BotonAnadirIngrediente = new javax.swing.JButton();
        BotonRegistrarProducto = new javax.swing.JButton();
        jLabelProducto = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelANADIRINGREDIENTES.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelANADIRINGREDIENTES.setText("AÑADIR INGREDIENTES");

        jLabelIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelIngrediente.setText("Ingrediente:");

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelCantidad.setText("Cantidad:");

        jComboBoxIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        BotonAnadirIngrediente.setBackground(new java.awt.Color(171, 118, 46));
        BotonAnadirIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        BotonAnadirIngrediente.setText("AÑADIR INGREDIENTE");
        BotonAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirIngredienteActionPerformed(evt);
            }
        });

        BotonRegistrarProducto.setBackground(new java.awt.Color(171, 118, 46));
        BotonRegistrarProducto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        BotonRegistrarProducto.setText("REGISTRAR PRODUCTO");
        BotonRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarProductoActionPerformed(evt);
            }
        });

        jLabelProducto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelProducto.setText("Producto:");

        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabelANADIRINGREDIENTES)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIngrediente)
                            .addComponent(jLabelCantidad)
                            .addComponent(jComboBoxIngrediente, 0, 175, Short.MAX_VALUE)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jLabelProducto)
                            .addComponent(jComboBoxProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelANADIRINGREDIENTES)
                .addGap(24, 24, 24)
                .addComponent(jLabelProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void BotonAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirIngredienteActionPerformed
        anadirIngredienteProducto();
    }//GEN-LAST:event_BotonAnadirIngredienteActionPerformed

    private void BotonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarProductoActionPerformed
        this.dispose(); // Cierra la ventana actual
        frmMenuPrincipal menu = new frmMenuPrincipal(); // Crea una nueva instancia del menú principal
        menu.setVisible(true); // Muestra el menú principal
    }//GEN-LAST:event_BotonRegistrarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnadirIngrediente;
    private javax.swing.JButton BotonRegistrarProducto;
    private javax.swing.JComboBox<String> jComboBoxIngrediente;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabelANADIRINGREDIENTES;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelIngrediente;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
