/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemarestaurantepresentacion.ModuloProductos;

import java.util.List;
import sistemarestaurantedominio.Ingrediente;
import sistemarestaurantedominio.Producto;
import sistemarestaurantedominio.UnidadMedidaIngrediente;
import sistemarestaurantepersistencia.DAOS_implementaciones.IngredientesDAO;
import sistemarestaurantepersistencia.DAOS_implementaciones.ProductosDAO;

/**
 *
 * @author gael_
 */
public class frmAnadirIngredienteProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmAnadirIngredienteProducto
     */
    public frmAnadirIngredienteProducto() {
        initComponents();
        LlenarComboBoxMedida();
        LlenarComboBoxIngrediente();
    }
    
        private void LlenarComboBoxProducto(){
        ProductosDAO productosDAO = new ProductosDAO();
        List<Producto> productos = productosDAO.obtenerProductos();
        
        jComboBoxProducto.removeAllItems();
        
        for(Producto producto : productos){
            jComboBoxProducto.addItem(producto.getNombre());
        }
    }
    
   private void LlenarComboBoxMedida(){
        for(UnidadMedidaIngrediente medida : UnidadMedidaIngrediente.values()){
            jComboBoxMedida.addItem(medida.toString());
        }
    }
   
    private void LlenarComboBoxIngrediente(){
        IngredientesDAO ingredienteDAO = new IngredientesDAO();
        List<Ingrediente> ingredientes = ingredienteDAO.obtenerIngredientes();
        
        jComboBoxIngrediente.removeAllItems();
        
        for(Ingrediente ingrediente : ingredientes){
            jComboBoxIngrediente.addItem(ingrediente.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelANADIRINGREDIENTES = new javax.swing.JLabel();
        jLabelSeleccionarProducto = new javax.swing.JLabel();
        jLabelIngrediente = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jLabelMedida = new javax.swing.JLabel();
        jComboBoxProducto = new javax.swing.JComboBox<>();
        jComboBoxIngrediente = new javax.swing.JComboBox<>();
        jTextFieldCantidad = new javax.swing.JTextField();
        jComboBoxMedida = new javax.swing.JComboBox<>();
        BotonAnadirIngrediente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelANADIRINGREDIENTES.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelANADIRINGREDIENTES.setText("AÑADIR INGREDIENTES");

        jLabelSeleccionarProducto.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelSeleccionarProducto.setText("Seleccionar Producto:");

        jLabelIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelIngrediente.setText("Ingrediente:");

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelCantidad.setText("Cantidad:");

        jLabelMedida.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelMedida.setText("Medida");

        jComboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        jComboBoxMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonAnadirIngrediente.setBackground(new java.awt.Color(171, 118, 46));
        BotonAnadirIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        BotonAnadirIngrediente.setText("AÑADIR INGREDIENTE");
        BotonAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirIngredienteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(171, 118, 46));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setText("REGISTRAR PRODUCTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabelANADIRINGREDIENTES)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelIngrediente)
                    .addComponent(jLabelSeleccionarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCantidad)
                    .addComponent(jLabelMedida)
                    .addComponent(jComboBoxProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxIngrediente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCantidad)
                    .addComponent(jComboBoxMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelANADIRINGREDIENTES)
                .addGap(42, 42, 42)
                .addComponent(jLabelSeleccionarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIngrediente)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMedida)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void BotonAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAnadirIngredienteActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnadirIngrediente;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxIngrediente;
    private javax.swing.JComboBox<String> jComboBoxMedida;
    private javax.swing.JComboBox<String> jComboBoxProducto;
    private javax.swing.JLabel jLabelANADIRINGREDIENTES;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelIngrediente;
    private javax.swing.JLabel jLabelMedida;
    private javax.swing.JLabel jLabelSeleccionarProducto;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
