/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemarestaurantepresentacion.ModuloProductos;

import java.util.List;
import javax.swing.JOptionPane;
import sistemarestaurantedominio.Ingrediente;
import static sistemarestaurantedominio.IngredienteProducto_.ingrediente;
import static sistemarestaurantedominio.IngredienteProducto_.producto;
import sistemarestaurantedominio.Producto;
import sistemarestaurantedominio.UnidadMedidaIngrediente;
import sistemarestaurantedominio.dtos.NuevoIngredienteProductoDTO;
import sistemarestaurantedominio.dtos.NuevoProductoDTO;
import sistemarestaurantepersistencia.DAOS_implementaciones.IngredientesDAO;
import sistemarestaurantepersistencia.DAOS_implementaciones.ProductosDAO;

/**
 *
 * @author gael_
 */
public class frmAnadirIngredienteProducto extends javax.swing.JFrame {

    private NuevoProductoDTO productoSeleccionado;

    /**
     * Creates new form frmAnadirIngredienteProducto
     */
    public frmAnadirIngredienteProducto(NuevoProductoDTO producto) {
        initComponents();
        this.productoSeleccionado = producto;
        LlenarComboBoxIngrediente();
    }
    


   
    private void LlenarComboBoxIngrediente(){
        IngredientesDAO ingredienteDAO = new IngredientesDAO();
        List<Ingrediente> ingredientes = ingredienteDAO.obtenerIngredientes();
        
        jComboBoxIngrediente.removeAllItems();
        
        
        for(Ingrediente ingrediente : ingredientes){
        String nombreCompleto = ingrediente.getNombre() + " - " + ingrediente.getUnidadMedida();
        jComboBoxIngrediente.addItem(nombreCompleto);
    }
    }
    
    public Ingrediente enviarIngredienteSeleccionado(){
        String seleccionado = (String) jComboBoxIngrediente.getSelectedItem();
        
        if (seleccionado != null) {
            IngredientesDAO ingredienteDAO = new IngredientesDAO();
            List<Ingrediente> ingredientes = ingredienteDAO.obtenerIngredientes();

            for (Ingrediente ingrediente : ingredientes) {
                String nombreCompleto = ingrediente.getNombre() + " - " + ingrediente.getUnidadMedida();
                if (nombreCompleto.equals(seleccionado)) {
                    return ingrediente;
                }
            }
        }    
    }
    
    private void anadirIngredienteProducto(){
        
        Float cantidad = Float.parseFloat(this.jTextFieldCantidad.getText());
        Ingrediente ingredienteSeleccionado = enviarIngredienteSeleccionado();

        
        if (ingredienteSeleccionado != null) {
        NuevoIngredienteProductoDTO nuevoIP = new NuevoIngredienteProductoDTO(productoSeleccionado, ingredienteSeleccionado, cantidad);
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un ingrediente válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelANADIRINGREDIENTES = new javax.swing.JLabel();
        jLabelIngrediente = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jComboBoxIngrediente = new javax.swing.JComboBox<>();
        jTextFieldCantidad = new javax.swing.JTextField();
        BotonAnadirIngrediente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelANADIRINGREDIENTES.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabelANADIRINGREDIENTES.setText("AÑADIR INGREDIENTES");

        jLabelIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelIngrediente.setText("Ingrediente:");

        jLabelCantidad.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabelCantidad.setText("Cantidad:");

        jComboBoxIngrediente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });

        BotonAnadirIngrediente.setBackground(new java.awt.Color(171, 118, 46));
        BotonAnadirIngrediente.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        BotonAnadirIngrediente.setText("AÑADIR INGREDIENTE");
        BotonAnadirIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirIngredienteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(171, 118, 46));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setText("REGISTRAR PRODUCTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabelANADIRINGREDIENTES))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelIngrediente)
                                .addComponent(jLabelCantidad)
                                .addComponent(jComboBoxIngrediente, 0, 175, Short.MAX_VALUE))
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelANADIRINGREDIENTES)
                .addGap(18, 18, 18)
                .addComponent(jLabelIngrediente)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BotonAnadirIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void BotonAnadirIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirIngredienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAnadirIngredienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAnadirIngrediente;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxIngrediente;
    private javax.swing.JLabel jLabelANADIRINGREDIENTES;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelIngrediente;
    private javax.swing.JTextField jTextFieldCantidad;
    // End of variables declaration//GEN-END:variables
}
