/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemarestaurantepresentacion.ModuloIngredientes;

import java.util.logging.Level;
import java.util.logging.Logger;
import sistemarestaurantenegocio.excepciones.NegocioException;

public class FrmMenuIngredientes extends javax.swing.JFrame {
    
    private ControlNavegacionIngredientes control;
    
    /**
     * Creates new form frmMenuIngredientes
     */
    public FrmMenuIngredientes(ControlNavegacionIngredientes control) {
        this.control=control;
        initComponents();
        setTitle("Menu ingredientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarIngrediente = new javax.swing.JLabel();
        pnlMenuIngredientes = new javax.swing.JPanel();
        btnRegistrarIngrediente = new javax.swing.JButton();
        btnBuscarIngrediente = new javax.swing.JButton();
        btnVolverMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBuscarIngrediente.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lblBuscarIngrediente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarIngrediente.setText("INGREDIENTE");

        pnlMenuIngredientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        btnRegistrarIngrediente.setText("REGISTRAR INGREDIENTE");
        btnRegistrarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIngredienteActionPerformed(evt);
            }
        });

        btnBuscarIngrediente.setText("BUSCAR INGREDIENTE");
        btnBuscarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIngredienteActionPerformed(evt);
            }
        });

        btnVolverMenuPrincipal.setText("VOLVER");
        btnVolverMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuIngredientesLayout = new javax.swing.GroupLayout(pnlMenuIngredientes);
        pnlMenuIngredientes.setLayout(pnlMenuIngredientesLayout);
        pnlMenuIngredientesLayout.setHorizontalGroup(
            pnlMenuIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuIngredientesLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addGroup(pnlMenuIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        pnlMenuIngredientesLayout.setVerticalGroup(
            pnlMenuIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuIngredientesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnRegistrarIngrediente)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarIngrediente)
                .addGap(74, 74, 74)
                .addComponent(btnVolverMenuPrincipal)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenuIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlMenuIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIngredienteActionPerformed
        // TODO add your handling code here:
        control.IniciarFrmRegistrarIngrediente();
        dispose();
    }//GEN-LAST:event_btnRegistrarIngredienteActionPerformed

    private void btnBuscarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngredienteActionPerformed
        try {
            // TODO add your handling code here:
            control.IniciarFrmBuscarIngredientes();
        } catch (NegocioException ex) {
            Logger.getLogger(FrmMenuIngredientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnBuscarIngredienteActionPerformed

    private void btnVolverMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuPrincipalActionPerformed
        // TODO add your handling code here:
        control.salir();
    }//GEN-LAST:event_btnVolverMenuPrincipalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIngrediente;
    private javax.swing.JButton btnRegistrarIngrediente;
    private javax.swing.JButton btnVolverMenuPrincipal;
    private javax.swing.JLabel lblBuscarIngrediente;
    private javax.swing.JPanel pnlMenuIngredientes;
    // End of variables declaration//GEN-END:variables
}
