package sistemarestaurantepresentacion.ModuloIngredientes;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemarestaurantedominio.UnidadMedidaIngrediente;
import sistemarestaurantedominio.dtos.NuevoIngredienteDTO;
import sistemarestaurantenegocio.IIngredientesBO;
import sistemarestaurantenegocio.excepciones.NegocioException;

public class FrmRegistrarIngrediente extends javax.swing.JFrame {
    private ControlNavegacionIngredientes control;
    private IIngredientesBO ingredientesBO;
    private static final Logger LOG = Logger.getLogger(FrmRegistrarIngrediente.class.getName());
    
    /**
     * Creates new form frmRegistrarIngrediente
     */
    public FrmRegistrarIngrediente(ControlNavegacionIngredientes control,IIngredientesBO ingredientesBO) {
        initComponents();
        this.control = control;
        this.ingredientesBO=ingredientesBO;
        this.llenarComboBoxMedida();
        setTitle("Registro ingredientes");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroIngrediente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        cmbUnidadMedida = new javax.swing.JComboBox<>();
        txtStock = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(241, 209, 165));
        setForeground(new java.awt.Color(241, 209, 165));

        pnlRegistroIngrediente.setBackground(new java.awt.Color(241, 209, 165));
        pnlRegistroIngrediente.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));
        pnlRegistroIngrediente.setForeground(new java.awt.Color(241, 209, 165));

        jLabel2.setText("Nombre");

        jLabel3.setText("UnIdad de medida");

        jLabel4.setText("Stock");

        btnRegistrar.setBackground(new java.awt.Color(220, 145, 79));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(220, 145, 79));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(241, 209, 165));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR INGREDIENTE");

        javax.swing.GroupLayout pnlRegistroIngredienteLayout = new javax.swing.GroupLayout(pnlRegistroIngrediente);
        pnlRegistroIngrediente.setLayout(pnlRegistroIngredienteLayout);
        pnlRegistroIngredienteLayout.setHorizontalGroup(
            pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroIngredienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(pnlRegistroIngredienteLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRegistroIngredienteLayout.setVerticalGroup(
            pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroIngredienteLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroIngredienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(54, 54, 54)
                .addComponent(btnRegresar)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistroIngrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlRegistroIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        control.IniciarFrmMenuIngredientes();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.registrarIngrediente();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    private void llenarComboBoxMedida(){
        for(UnidadMedidaIngrediente unidadMedida : UnidadMedidaIngrediente.values()){
            this.cmbUnidadMedida.addItem(unidadMedida.toString());
        }
    }
    
    private void registrarIngrediente(){
        String nombreIngrediente = this.txtNombreIngrediente.getText();
        String unidadMedida = this.cmbUnidadMedida.getSelectedItem().toString();
        String sotck = this.txtStock.getText();
        
        
        
        try {
            Float stockFloat = Float.valueOf(sotck);
            NuevoIngredienteDTO nuevoIngrediente = new NuevoIngredienteDTO(nombreIngrediente, UnidadMedidaIngrediente.valueOf(unidadMedida), stockFloat);
            this.ingredientesBO.registrarIngrediente(nuevoIngrediente);
            control.IniciarFrmMensajeRegistroIngredienteExitoso();
            dispose();
            
        } catch (NegocioException e) {
            LOG.severe("No fue posible registrar el ingrediente: " + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error" , JOptionPane.WARNING_MESSAGE);
            
        }catch (NumberFormatException e) {
            LOG.severe("No fue posible registrar el ingrediente: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "El stock debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }    
        this.limpiarFormulario();
    }
    
    private void limpiarFormulario(){
        this.txtNombreIngrediente.setText("");
        this.txtStock.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnlRegistroIngrediente;
    private javax.swing.JTextField txtNombreIngrediente;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
